### ISSUE TITLE
Will this work with 3.12.20?

### ISSUE THREAD

**Issue by KingScooty** [mwelchuk/usbtv#1]
Will this work with 3.12.20? Or will it need to be backported again? Looking to use it with my Raspberry Pi (Wheezy).

**Comment by mwelchuk** [comment]
The latest version of the usbtv driver is provided in the kernel source tree, no porting is required. Is the problem more that it's not built and provided as a binary kernel module with the Raspberry Pi Kernel build?

**Comment by KingScooty** [comment]
Oh right! I'm not too sure! How would i check? 
My EasyCap (USBTV007) doesn't seem to be getting detected by my Raspberry Pi at the moment, which suggests it's not, unless i'm doing something wrong.
